# Don't print a new line at the start of the prompt
add_newline = false

[character]
format = "$symbol[::](bold fg:#80E544)"
success_symbol = "[  ](bold fg:#8ec07c)" 
error_symbol = "[  ](bold fg:#fb4934)"
vicmd_symbol = "[  ](bold fg:#b8bb26)"

[package]
format = "via [ $version](208 bold) "

[lua]
format = "via [](bold fg:#0000ff) [$version](bold blue)"

[rust]
format = "via [ $version](red bold)"

[crystal]
format = "via [ $version](black bold)"

[ocaml]
format = "via [ $version](208 bold) "
