#!/bin/bash

gsc_version="0.1.0"

# Check if trizen is installed on the system
if ! command -v trizen &> /dev/null
then
    echo "trizen is not installed on your system! gsc need trizen to run properly."
    read -p "do you want to install it now?(y/n):" userinput
    case $userinput in
        [yY]*)
          doas pacman -S trizen ;;
        [nN]*) exit;;
          *)
          echo "wrong input!"
          exit;;
      esac
fi

function resync () {
  trizen -Sy
}

switch=$1

case $switch in
  "sync")
    ./gsc-sync;;
  "version")
    echo "gsc - Pacman and Trizen layer 
      version $gsc_version"
esac

